### ISSUE TITLE
Traefik auto SSL с n8n и redsocks – как настроить?

### ISSUE THREAD

**Issue by mugukamil** [brahmic/xn8n#1]
Привет,

Использую ваш проект (n8n + redsocks + Xray) для проксирования исходящего трафика n8n. Хочу добавить Traefik для автоматического получения SSL-сертификатов (Let's Encrypt).

Проблема:
Есть опасение, что redsocks будет мешать Traefik проходить ACME-проверки, так как весь трафик n8n идет через него.

Вопрос:
Как правильно настроить Traefik для авто-SSL в такой конфигурации, чтобы redsocks не мешал, но основной трафик n8n продолжал идти через Xray? Есть ли какие-то советы или примеры конфигурации redsocks для обхода трафика ACME-проверок?

Спасибо!

пример docker-compose.yml
```
services:
  n8n:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: ${APP_NAME:-xn8n}-n8n
    # Все переменные окружения из .env автоматически передаются в контейнер
    environment:
      - N8N_HOST=${SUBDOMAIN}.${DOMAIN_NAME}
      - N8N_PORT=5678
      - N8N_PROTOCOL=https
      - NODE_ENV=production
      - N8N_RUNNERS_ENABLED=true
      - WEBHOOK_URL=https://${SUBDOMAIN}.${DOMAIN_NAME}/
      - GENERIC_TIMEZONE=${GENERIC_TIMEZONE}
    volumes:
      # Основные данные (обязательно)
      - n8n_data:/home/node/.n8n
      
      # Дополнительные тома
      - ../../data/n8n/uploads:/home/node/files           # Для файлов
      - ../../data/n8n/custom_nodes:/home/node/.n8n/custom  # Кастомные ноды
      - ../../data/n8n/certs:/home/node/.n8n/certs        # Сертификаты
    depends_on:
      redsocks:
        condition: service_healthy
    network_mode: "service:redsocks"  # Используем сеть контейнера redsocks
    # networks:
    #   - internal
    # ports:
    #   - "127.0.0.1:${N8N_PORT}:5678"
    
  
  # traefik:
  #   image: "traefik"
  #   restart: always
  #   networks:
  #     - internal
  #   command:
  #     - "--api.insecure=true"
  #     - "--providers.docker=true"
  #     - "--providers.docker.exposedbydefault=false"
  #     - "--entrypoints.web.address=:80"
  #     - "--entrypoints.web.http.redirections.entryPoint.to=websecure"
  #     - "--entrypoints.web.http.redirections.entrypoint.scheme=https"
  #     - "--entrypoints.websecure.address=:443"
  #     - "--certificatesresolvers.mytlschallenge.acme.tlschallenge=true"
  #     - "--certificatesresolvers.mytlschallenge.acme.email=${SSL_EMAIL}"
  #     - "--certificatesresolvers.mytlschallenge.acme.storage=/letsencrypt/acme.json"
  #   ports:
  #     - "80:80"
  #     - "443:443"
  #   volumes:
  #     - traefik_data:/letsencrypt
  #     - /var/run/docker.sock:/var/run/docker.sock:ro

  redsocks:
    image: alpine:latest     
    build:
      context: ../..
      dockerfile: src/docker/images/redsocks/Dockerfile.redsocks
    container_name: ${APP_NAME:-xn8n}-redsocks
    networks:
      - internal
    ports:
      - "127.0.0.1:${N8N_PORT}:5678"  # Порт для n8n
    command: sh /etc/init.sh
    volumes:
      - ../../src/docker/images/redsocks/redsocks.conf:/etc/redsocks.conf
      - ../../src/scripts/init.sh:/etc/init.sh
      - ../../logs/redsocks:/var/log/redsocks
    cap_add:
      - NET_ADMIN
    privileged: true
    depends_on:
      xray:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "sh", "-c", "ps aux | grep redsocks | grep -v grep"]
      interval: 5s
      timeout: 3s
      retries: 10
      start_period: 5s

  xray:
    image: teddysun/xray
    container_name: ${APP_NAME:-xn8n}-xray
    networks:
      - internal
    # Порты не публикуются наружу, доступны только внутри сети Docker
    volumes:
      - ../../data/xray/config.json:/etc/xray/config.json
      - ../../logs/xray:/var/log/xray
    healthcheck:
      test: ["CMD", "sh", "-c", "ps aux | grep xray | grep -v grep"]
      interval: 5s
      timeout: 3s
      retries: 10
      start_period: 5s

networks:
  internal:
    driver: bridge

volumes:
  n8n_data:
    driver: local
  traefik_data:
```

**Comment by mugukamil** [comment]
проблема решилась переносом меток из n8n в redsocks:
```
  redsocks:
    # image: alpine:latest # Это будет переопределено контекстом сборки, если Dockerfile.redsocks его использует
    build:
      context: ../.. # Убедитесь, что этот путь корректен относительно вашего docker-compose.yml
      dockerfile: src/docker/images/redsocks/Dockerfile.redsocks
    container_name: ${APP_NAME:-xn8n}-redsocks
    networks:
      - internal # Этот сервис находится в сети 'internal'
    ports:
      # Это порт, на котором слушает n8n (работающий в сетевом пространстве redsocks).
      # Traefik будет обращаться к IP сервиса redsocks на этот порт.
      # Внутренний порт - это фактический порт прослушивания n8n (5678).
      # Внешний порт - это то, что будет использовать Traefik. Сделаем его явным.
      # Переменная N8N_PORT_ON_REDSOCKS_FOR_TRAEFIK может быть задана в .env, по умолчанию 5678.
      - "${N8N_PORT_ON_REDSOCKS_FOR_TRAEFIK:-5678}:5678"
    command: sh /etc/init.sh # Команда для запуска redsocks и настройки iptables
    volumes:
      - ../../src/docker/images/redsocks/redsocks.conf:/etc/redsocks.conf
      - ../../src/scripts/init.sh:/etc/init.sh
      - ../../logs/redsocks:/var/log/redsocks
    cap_add:
      - NET_ADMIN # Необходимо для работы с iptables
    privileged: true # Часто требуется для расширенных манипуляций с iptables/сетью
    depends_on:
      xray:
        condition: service_healthy
    labels: # Метки Traefik размещаются на сервисе redsocks, так как n8n использует его сетевое пространство
      - "traefik.enable=true"
      - "traefik.docker.network=internal" # Явно указываем Traefik использовать эту сеть для данного сервиса

      # HTTPS Роутер для n8n
      - "traefik.http.routers.${APP_NAME:-xn8n}-n8n-https.rule=Host(`${SUBDOMAIN}.${DOMAIN_NAME}`)"
      - "traefik.http.routers.${APP_NAME:-xn8n}-n8n-https.entrypoints=websecure"
      - "traefik.http.routers.${APP_NAME:-xn8n}-n8n-https.tls=true"
      - "traefik.http.routers.${APP_NAME:-xn8n}-n8n-https.tls.certresolver=mytlschallenge"
      # Определение сервиса для n8n
      - "traefik.http.services.${APP_NAME:-xn8n}-n8n-service.loadbalancer.server.port=${N8N_PORT_ON_REDSOCKS_FOR_TRAEFIK:-5678}"
      # Если вам нужен отдельный HTTP роутер для редиректа (глобальный редирект уже настроен в командах Traefik):
      # - "traefik.http.routers.${APP_NAME:-xn8n}-n8n-http.rule=Host(`${SUBDOMAIN}.${DOMAIN_NAME}`)"
      # - "traefik.http.routers.${APP_NAME:-xn8n}-n8n-http.entrypoints=web"
      # - "traefik.http.routers.${APP_NAME:-xn8n}-n8n-http.middlewares=redirect-to-https@docker"
      # - "traefik.http.middlewares.redirect-to-https.redirectscheme.scheme=https"
      # - "traefik.http.middlewares.redirect-to-https.redirectscheme.permanent=true
```
